### PR TITLE
Add support for the popular uEditorNotes property editor

### PR DESCRIPTION
**Pull request by marcemarc**
And also one that will go to the even more popular Contentment one

### CODE REVIEW

**Comment by KevinJump** [comment]
I just need to work out how we handle having two migrators for the same thing now 😄

**Comment by leekelleher** [comment]
There'd have to be a default one, with the other available to replace it. Most like use the `HideFromTypeFinder` attribute, then swap them in a Composer (I know, dev skill, not UI 🫤)

**Comment by marcemarc** [comment]
Pragmatically - we could just PR the one that goes to Contentment? (do you have collapsible notes yet @leekelleher ?) - I did the like for like, one mainly to just see what was involved, but if we have that collapsibility feature we can retire uEditorNotes!

**Comment by leekelleher** [comment]
@marcemarc No collapsible notes yet, I can't quite bring myself to say goodbye to you maintaining uEditorNotes. 😢 

Interesting though, is it possible for Contentment to have an `ISyncPropertyMigrator`, without forcing a hard dependency on uSync Migrations? (from my previous research on .NET Fx it wasn't possible, but unsure about .NET Core world) 🤔

**Comment by marcemarc** [comment]
@leekelleher but I'll have to do 'all the things' to make it appear in the new marketplace... although might be worth it to see my dodgy crow logo in there...

**Comment by prjseal** [comment]
You can't drop the award winning package uEditorNotes for the sake of a bit of admin 😄

**Pull request merged**
